# Generated by Django 4.0.5 on 2026-08-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursesubmissionviewablemember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesettings',
            name='show_ai_score',
            field=models.BooleanField(default=False, help_text='If False (default), students only see AI text suggestions, not numeric scores (score_json). Teachers always see scores.'),
        ),
    ]
