# Generated by Django 4.0.5 on 2025-10-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackinitialresponse',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackinitialresponse',
            name='mechanic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
