# Generated by Django 4.0.5 on 2026-08-18 14:36

from django.db import migrations, models
import django.db.models.deletion
import pigeonhole.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursesubmissionviewablemember_and_more'),
        ('feedback', '0002_feedbackinitialresponse_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAnswerVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=1000)),
                ('answer_content', models.TextField()),
                ('version_number', models.PositiveIntegerField()),
                ('genre', models.TextField(blank=True, null=True)),
                ('mechanic', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursemembership')),
                ('milestone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursemilestone')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursemilestonetemplate')),
            ],
            options={
                'unique_together': {('course', 'milestone', 'template', 'creator', 'question', 'version_number')},
            },
            bases=(pigeonhole.common.utils.UpdateFromDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AIFeedbackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.CharField(choices=[('REFLECTION', 'Reflection writing feedback'), ('PLAYTEST', 'Playtest feedback')], max_length=20)),
                ('strategy', models.CharField(choices=[('BASIC', 'Basic prompt'), ('ADVANCED', 'Advanced prompt'), ('PLAYTEST', 'Playtest (LightRAG)')], max_length=20)),
                ('score_json', models.JSONField(blank=True, null=True)),
                ('feedback_content', models.TextField()),
                ('model_version', models.CharField(blank=True, default='', max_length=255)),
                ('token_usage_json', models.JSONField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_records', to='feedback.feedbackanswerversion')),
            ],
            options={
                'abstract': False,
            },
            bases=(pigeonhole.common.utils.UpdateFromDictMixin, models.Model),
        ),
    ]
