# Generated by Django 4.0.5 on 2026-08-30 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursesettings_show_ai_score'),
        ('feedback', '0003_feedbackanswerversion_aifeedbackrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackanswerversion',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_answer_versions', to='courses.coursesubmission'),
        ),
    ]
